// example/vue2/src/PixProSkin/components/AngleAdjustment.vue
<template>
  <div class="rotate-ruler" @wheel="handleWheel" @mousedown="startDrag" @mousemove="handleDrag" @mouseup="stopDrag" @mouseleave="stopDrag">
    <div class="slide-container" :style="{ height: `${(maxAngle / 3) * 9}px`, ...rulerStyle }">
      <div class="ruler-content">
        <!-- 数字和刻度 -->
        <div class="ruler-scale">
          <div v-for="n in maxAngle / 3 + 1" :key="n" class="scale-row">
            <!-- 数字每15度(5个刻度)一个 -->
            <div class="number-cell">
              <span v-if="(n - 1) % 5 === 0">{{ (n - 1) * 3 - maxAngle / 2 }}°</span>
            </div>
            <!-- 刻度 -->
            <div class="scale-cell" :class="{ 'major-scale': (n - 1) % 5 === 0 }">
              <div class="scale-line"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="ruler-pointer"><svg-icon name="pointer" /></div>
  </div>
</template>

<script>
import SvgIcon from "./SvgIcon.vue";

export default {
  components: {
    SvgIcon,
  },
  props: {
    value: {
      type: Number,
      default: 0,
    },
    maxAngle: {
      type: Number,
      required: true,
    },
    snapThreshold: {
      type: Number,
      default: 5,
    },
  },
  data() {
    return {
      isDragging: false,
      startY: 0,
      startAngle: 0,
      isSnapping: false,
    };
  },
  computed: {
    rulerStyle() {
      // 每个刻度代表3度，每个刻度高度为9px
      const pixelPerDegree = 3; // 每度对应的像素数

      // 将角度值映射到刻度尺的位置
      // 在这里，当角度为0时，我们希望0°刻度对准角标指针
      const offset = -this.value * pixelPerDegree;

      return {
        transform: `translateY(${offset}px)`,
        transition: this.isSnapping ? "transform 200ms ease-out" : "none",
      };
    },
  },
  methods: {
    checkSnap(angle) {
      if (Math.abs(angle) <= this.snapThreshold) {
        this.isSnapping = true;
        setTimeout(() => {
          this.isSnapping = false;
        }, 200);
        return 0;
      }
      this.isSnapping = false;
      return angle;
    },
    handleWheel(e) {
      e.preventDefault();

      // 根据当前角度是否在吸附范围内动态调整粒度
      const step = Math.abs(this.value) <= this.snapThreshold ? 6 : 3;
      const direction = e.deltaY > 0 ? 1 : -1; // 反向滚动方向
      const newValue = Math.max(-this.maxAngle / 2, Math.min(this.maxAngle / 2, this.value + direction * step));

      // 如果正在吸附动画中，不处理滚轮事件
      if (this.isSnapping) return;

      // 检查是否需要吸附
      const snappedValue = this.checkSnap(newValue);
      if (snappedValue !== newValue) {
        this.$emit("input", snappedValue);
      } else {
        this.$emit("input", newValue);
      }
    },
    startDrag(e) {
      this.isDragging = true;
      this.startY = e.clientY;
      this.startAngle = this.value;
    },
    handleDrag(e) {
      if (!this.isDragging) return;
      const deltaY = this.startY - e.clientY; // 反向拖拽方向
      const newAngle = this.startAngle + Math.round(deltaY / 3);
      this.$emit("input", this.checkSnap(Math.max(-this.maxAngle / 2, Math.min(this.maxAngle / 2, newAngle))));
    },
    stopDrag() {
      if (this.isDragging) {
        const snappedValue = this.checkSnap(this.value);
        if (snappedValue !== this.value) {
          this.$emit("input", snappedValue);
        }
      }
      this.isDragging = false;
    },
  },
};
</script>

<style lang="less" scoped>
.rotate-ruler {
  width: 54px;
  height: 100%;
  display: flex;
  align-items: center;
  position: relative;
  overflow: hidden;
  cursor: ns-resize;
  user-select: none;

  &:after,
  &:before {
    content: "";
    position: absolute;
    left: 0;
    width: 100%;
    height: calc(50% - 100px);
    z-index: 1;
    pointer-events: none;
  }

  &:before {
    top: 0;
    background: linear-gradient(to bottom, rgba(249, 249, 249, 1) 0%, rgba(249, 249, 249, 1) 80%, rgba(249, 249, 249, 0.8) 90%, rgba(249, 249, 249, 0) 100%);
  }

  &:after {
    bottom: 0;
    background: linear-gradient(to bottom, rgba(249, 249, 249, 0) 0%, rgba(249, 249, 249, 0.8) 10%, rgba(249, 249, 249, 1) 20%, rgba(249, 249, 249, 1) 100%);
  }

  .slide-container {
    width: 100%;
    height: 540px;
    position: relative;
    left: -12px;
    top: -4px;
  }

  .ruler-content {
    width: 100%;
    height: 100%;
  }

  .ruler-scale {
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;

    .scale-row {
      height: 9px;
      width: 100%;
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    .number-cell {
      flex: 1;
      height: 9px;
      display: flex;
      align-items: center;
      justify-content: flex-end;

      span {
        font-size: 12px;
        width: 34px;
        text-align: right;
        padding-right: 4px;
        color: rgba(42, 50, 70, 0.7);
      }
    }

    .scale-cell {
      width: 16px;
      height: 9px;
      display: flex;
      align-items: center;
      position: relative;

      .scale-line {
        height: 2px;
        background-color: rgba(42, 50, 70, 0.2);
        position: absolute;
        right: 4px;
        width: 5px;
        border-radius: 1px;
      }

      &.major-scale {
        .scale-line {
          width: 9px;
          right: 0px;
          background-color: rgba(42, 50, 70, 0.5);
        }
      }
    }
  }

  .ruler-pointer {
    position: absolute;
    width: 14px;
    height: 14px;
    right: 0;
    top: 50%;
    transform: translateY(-50%);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 2;
    margin-right: 0;
  }
}
</style>

// example/react/src/PixProSkin/AngleAdjustment.tsx
import React, { useState } from "react";
import SvgIcon from "./SvgIcon";
import "./AngleAdjustment.less";

interface AngleAdjustmentProps {
  value: number;
  onChange: (value: number) => void;
  maxAngle: number;
  snapThreshold?: number;
  onHandleRemindImage?: (visible: boolean) => void;
}

const AngleAdjustment: React.FC<AngleAdjustmentProps> = ({ value, onChange, maxAngle, snapThreshold = 5, onHandleRemindImage }) => {
  const [isDragging, setIsDragging] = useState(false);
  const [startY, setStartY] = useState(0);
  const [startAngle, setStartAngle] = useState(0);
  const [isSnapping, setIsSnapping] = useState(false);

  const rulerStyle = {
    height: `${(maxAngle / 3) * 9}px`,
    transform: `translateY(${value * 3}px)`,
    transition: isSnapping ? "transform 200ms ease-out" : "none",
  };

  const checkSnap = (angle: number, shouldSnap: boolean = false, dragDistance: number = 0): number => {
    if (shouldSnap && dragDistance > 3 && Math.abs(angle) <= 3) {
      setIsSnapping(true);
      setTimeout(() => {
        setIsSnapping(false);
      }, 200);
      return 0;
    }
    setIsSnapping(false);
    return angle;
  };

  const handleWheel = (e: React.WheelEvent) => {
    e.preventDefault();

    const step = Math.abs(value) <= 1 ? 6 : 3;
    const direction = e.deltaY > 0 ? -1 : 1;
    let newValue = Math.max(-maxAngle / 2, Math.min(maxAngle / 2, value + direction * step));

    if (Math.abs(newValue) <= 1) {
      newValue = 0;
      setIsSnapping(true);
      setTimeout(() => setIsSnapping(false), 200);
    }

    onHandleRemindImage?.(true);
    onChange(newValue);
  };

  const startDrag = (e: React.MouseEvent) => {
    setIsDragging(true);
    setStartY(e.clientY);
    setStartAngle(value);
    onHandleRemindImage?.(true);
  };

  const handleDrag = (e: React.MouseEvent) => {
    if (!isDragging) return;
    const deltaY = startY - e.clientY;

    const newAngle = startAngle - Math.round(deltaY / 3);
    const boundedAngle = Math.max(-maxAngle / 2, Math.min(maxAngle / 2, newAngle));
    const dragDistance = Math.abs(boundedAngle - startAngle);

    const snappedAngle = checkSnap(boundedAngle, true, dragDistance);
    onChange(snappedAngle);
  };

  const stopDrag = () => {
    if (isDragging) {
      onHandleRemindImage?.(false);
    }
    setIsDragging(false);
  };

  return (
    <div className="rotate-ruler" onWheel={handleWheel} onMouseDown={startDrag} onMouseMove={handleDrag} onMouseUp={stopDrag} onMouseLeave={stopDrag}>
      <div className="slide-container" style={rulerStyle}>
        <div className="ruler-content">
          <div className="ruler-scale">
            {Array.from({ length: maxAngle / 3 + 1 }).map((_, index) => (
              <div key={index} className="scale-row">
                <div className="number-cell">{index % 5 === 0 && <span>{index * 3 - maxAngle / 2}°</span>}</div>
                <div className={`scale-cell ${index % 5 === 0 ? "major-scale" : ""}`}>
                  <div className="scale-line"></div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className="ruler-pointer">
        <SvgIcon name="pointer" />
      </div>
    </div>
  );
};

export default AngleAdjustment;
